### ISSUE TITLE
RunTimeError when setting MS variable if MS doesn't exist. 

### ISSUE THREAD

**Issue by SpheMakh** [ska-sa/pyxis#24]
This is not good when running a simulation, because I usually set the MS name before I create the MS. I'm not sure why this happens since the line in question (line 462 in *ms.py*) is within a try-catch clause. 
![ms_issue](https://cloud.githubusercontent.com/assets/6624280/5942958/a1f29296-a723-11e4-99c6-24e3c3426bc2.png)

**Comment by o-smirnov** [comment]
Ah, but there's a ```traceback.print_exc()``` in the except clause there which prints the exception anyway, just for the user's reference. So this is annoying but harmless. I should add a print statement after print_exc() though to clarify this situation, since the output looks exactly like a fatal error.

Better yet: add this at line 460 (can't check it myself at the moment)

```
if not exists(MS):
  warn("$MS doesn't exist"); 
  return None;
```

for a kinder, gentler output in this simple case. That way the exception only shows up for the really screwy situations such as corrupt MSs.

**Comment by SpheMakh** [comment]
Done

**Comment by o-smirnov** [comment]
Wow, quick. :)
