### ISSUE TITLE
Applying primary beam led to subtracting the model sources totally

### ISSUE THREAD

**Issue by Ermiasabebe** [ska-sa/pyxis#53]
When I use primary beam model in my calibration pipeline, there will be a negative flux density in the residual image at the positions of the initial model sources. In other words, there is an over-cleaning at the position of each source. I have changed the iteration, but the result is the same.

Can this be due to the primary beam model ? The calibration works well without implementing the primary beam. Any suggestion on this issue?

**Comment by o-smirnov** [comment]
Strictly speaking, it's oversubtraction, not overcleaning. That is, the flux in the LSM is overestimated, so too much is subtracted. This happens before any cleaning is done (so you should be able to see holes in the dirty image as well).

As to why this happens -- are you sure you've enabled the primary beam properly? Two things have to work correctly:

1. The "apparent" fluxes measured by PyBDSM are converted (by ``tigger-convert``) into "intrinsic" fluxes, by dividing them by the average power beam towards each source.  The intrinsic flux is always higher than apparent, since the beam is <1 everywhere (well, it's exactly 1 at dead centre).

2. The new "instrinsic flux" LSM is used in the calibration, with the rotating primary beam applied to each source as it is being subtracted.

The mean of the rotating primary beam is exactly what's used to compute the average power beam at step 1, so the two steps should approximately cancel out. However, you say sources are oversubtracted -- this makes me suspect that you haven't enabled the beams at step 2 properly. If they're not enabled, then everything will be subtracted with a beam gain of 1, which is consistent with what you're seeing.

**Comment by o-smirnov** [comment]
BTW please file future issues of this nature under https://github.com/ratt-ru/calibration-pipelines. This is a pipelines problem not a pyxis one.
